// Auto-generates a session title from the first completed assistant turn,
// once per session, skipping sessions whose title was already customized.
import { useCallback, useRef } from 'react';
import { loadFullSession, updateSessionMeta } from '@/lib/sessions';
import { buildTitleSample, isAutoGeneratedTitle } from '@/lib/title';
import { partsToContent, type ChatMessage } from '@/lib/chat';
import type { SendArgs } from './types';

export interface AutoTitleStoreDeps {
  messagesBySession: React.MutableRefObject<Map<string, ChatMessage[]>>;
  lastSendBySession: React.MutableRefObject<Map<string, { args: SendArgs; assistantId: string }>>;
  titleBySession: React.MutableRefObject<Map<string, string | undefined>>;
}

export function useAutoTitle(deps: AutoTitleStoreDeps) {
  const { messagesBySession, lastSendBySession, titleBySession } = deps;
  /** Sessions for which we've already kicked title generation. */
  const titledRef = useRef<Set<string>>(new Set());

  const maybeAutoGenerateTitle = useCallback(async (sid: string) => {
    if (titledRef.current.has(sid)) return;

    const last = lastSendBySession.current.get(sid);
    const slug = last?.args.connection.slug;
    if (!slug) return;

    const allMessages = messagesBySession.current.get(sid) ?? [];
    const completedAssistantTurns = allMessages.filter(
      (m) => m.role === 'assistant' && !m.errorInfo && !m.isStreaming,
    ).length;
    if (completedAssistantTurns !== 1) return; // only on the very first turn

    const firstUser = allMessages.find((m) => m.role === 'user');
    if (!firstUser) return;
    const firstUserText = partsToContent(firstUser.parts);

    const data = await loadFullSession(sid);
    if (!data) return;
    if (!isAutoGeneratedTitle(data.meta.title, firstUserText)) return;

    titledRef.current.add(sid);
    try {
      const title = await window.api.chat.generateTitle({
        connectionSlug: slug,
        messages: buildTitleSample(allMessages),
        sessionId: sid,
        cwd: data.meta.workingDirectory,
      });
      if (title) {
        await updateSessionMeta(sid, { title });
        titleBySession.current.set(sid, title);
      }
    } catch {
      titledRef.current.delete(sid); // allow retry next turn on transient failures
    }
  }, [messagesBySession, lastSendBySession, titleBySession]);

  return { maybeAutoGenerateTitle };
}
