import {useCallback, useEffect, useRef, useState} from 'react';
import {chatFromStored, type ChatMessage, chatToStored, type MessagePart, newId, partsToContent,} from '@/lib/chat';
import {appendMessage, createSession, loadFullSession, replaceLastMessage, rewriteMessages, truncateSessionMessages, updateSessionMeta,} from '@/lib/sessions';
import { buildTitleSample, isAutoGeneratedTitle } from '@/lib/title';
import type {
  AgentError,
  ChatStreamEvent,
  NestedChatStreamEvent,
  ConnectionMeta,
  DraftAttachment,
  PermissionMode,
  StoredAttachment,
  StoredMessage,
  Plan,
  Phase,
  PlanRevision,
} from '@/lib/electron';
import { storeAttachment } from '@/lib/attachments';
import { getAppSettings } from '@/lib/app-settings';

interface SendArgs {
  text: string;
  connection: ConnectionMeta;
  model: string;
  /** Working directory the agent should operate in (per-session). */
  cwd?: string;
  /** Bound for tool-use loops in this turn. */
  maxTurns?: number;
  /** Permission mode for this turn ('plan' | 'auto'). */
  permissionMode: PermissionMode;
  /** Draft attachments — persisted to the session before send. */
  attachments?: DraftAttachment[];
  /**
   * If set, this is what the agent receives. The user-visible message
   * still shows `text`. Used by surfaces like the New Skill dialog to
   * keep scaffold context out of the chat transcript.
   */
  agentText?: string;
  /**
   * Origin tag — surfaced as a small chip above the user bubble. Drives
   * UI grouping for non-chat-originated submissions (e.g. 'add-skill').
   */
  intentTag?: string;
}

/* ---------- parts reducer --------------------------------------- */

function applyNestedEvent(parts: MessagePart[], evt: NestedChatStreamEvent): {
  parts: MessagePart[];
  usage?: ChatMessage['usage'];
  latestCallUsage?: ChatMessage['latestCallUsage'];
  stopReason?: string;
  error?: string;
  errorInfo?: AgentError;
  isStreaming?: boolean;
} {
  switch (evt.type) {
    case 'text_delta':
    case 'text_complete': {
      const last = parts[parts.length - 1];
      if (last && last.kind === 'text') {
        const updated: MessagePart = { kind: 'text', text: last.text + evt.text };
        return { parts: [...parts.slice(0, -1), updated] };
      }
      return { parts: [...parts, { kind: 'text', text: evt.text }] };
    }
    case 'thinking_delta': {
      const last = parts[parts.length - 1];
      if (last && last.kind === 'thinking') {
        const updated: MessagePart = {
          kind: 'thinking',
          text: last.text + evt.text,
          collapsed: last.collapsed,
        };
        return { parts: [...parts.slice(0, -1), updated] };
      }
      return { parts: [...parts, { kind: 'thinking', text: evt.text, collapsed: true }] };
    }
    case 'tool_start': {
      const idx = parts.findIndex((p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId);
      const existing = idx >= 0 ? (parts[idx] as Extract<MessagePart, { kind: 'tool' }>) : null;
      const next: MessagePart = existing
        ? { ...existing, name: evt.name, input: evt.input ?? existing.input }
        : {
            kind: 'tool',
            toolUseId: evt.toolUseId,
            name: evt.name,
            input: evt.input,
            status: 'running',
          };
      return {
        parts: idx >= 0
          ? [...parts.slice(0, idx), next, ...parts.slice(idx + 1)]
          : [...parts, next],
      };
    }
    case 'tool_input_delta': {
      const idx = parts.findIndex((p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId);
      if (idx < 0) return { parts };
      const tool = parts[idx] as Extract<MessagePart, { kind: 'tool' }>;
      const next: MessagePart = {
        ...tool,
        partialInputJson: (tool.partialInputJson ?? '') + evt.partialJson,
      };
      if (!tool.input) {
        try {
          next.input = JSON.parse(next.partialInputJson ?? '');
        } catch {
          /* partial only */
        }
      }
      return { parts: [...parts.slice(0, idx), next, ...parts.slice(idx + 1)] };
    }
    case 'tool_result': {
      const idx = parts.findIndex((p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId);
      if (idx < 0) return { parts };
      const tool = parts[idx] as Extract<MessagePart, { kind: 'tool' }>;
      const next: MessagePart = {
        ...tool,
        result: { content: evt.content, isError: evt.isError },
        status: evt.isError ? 'error' : 'done',
      };
      return { parts: [...parts.slice(0, idx), next, ...parts.slice(idx + 1)] };
    }
    case 'assistant_usage':
      return { parts, latestCallUsage: evt.usage };
    case 'turn_done':
      return {
        parts,
        usage: evt.usage,
        stopReason: evt.stopReason ?? 'stop',
        isStreaming: false,
      };
    case 'error':
      return {
        parts,
        error: evt.error.message,
        errorInfo: evt.error,
        isStreaming: false,
      };
    default:
      return { parts };
  }
}

/**
 * Apply one streaming event to a chat message's parts. Returns the next
 * message; structural-share when nothing changed so React can skip work.
 */
function applyEvent(msg: ChatMessage, evt: ChatStreamEvent): ChatMessage {
  switch (evt.type) {
    case 'text_delta':
    case 'text_complete': {
      const last = msg.parts[msg.parts.length - 1];
      if (last && last.kind === 'text') {
        const updated: MessagePart = {
          kind: 'text',
          text: last.text + evt.text,
        };
        return { ...msg, parts: [...msg.parts.slice(0, -1), updated] };
      }
      return {
        ...msg,
        parts: [...msg.parts, { kind: 'text', text: evt.text }],
      };
    }
    case 'thinking_delta': {
      const last = msg.parts[msg.parts.length - 1];
      if (last && last.kind === 'thinking') {
        const updated: MessagePart = {
          kind: 'thinking',
          text: last.text + evt.text,
          collapsed: last.collapsed,
        };
        return { ...msg, parts: [...msg.parts.slice(0, -1), updated] };
      }
      return {
        ...msg,
        parts: [
          ...msg.parts,
          { kind: 'thinking', text: evt.text, collapsed: true },
        ],
      };
    }
    case 'tool_start': {
      // De-dupe: if we've already pushed this toolUseId (e.g. via a previous
      // stream_event), update its input rather than appending a new card.
      const idx = msg.parts.findIndex(
        (p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId,
      );
      const existing = idx >= 0 ? (msg.parts[idx] as Extract<MessagePart, { kind: 'tool' }>) : null;
      const next: MessagePart = existing
        ? { ...existing, name: evt.name, input: evt.input ?? existing.input }
        : {
            kind: 'tool',
            toolUseId: evt.toolUseId,
            name: evt.name,
            input: evt.input,
            status: 'running',
          };
      const parts =
        idx >= 0
          ? [...msg.parts.slice(0, idx), next, ...msg.parts.slice(idx + 1)]
          : [...msg.parts, next];
      return { ...msg, parts };
    }
    case 'tool_input_delta': {
      const idx = msg.parts.findIndex(
        (p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId,
      );
      if (idx < 0) return msg;
      const tool = msg.parts[idx] as Extract<MessagePart, { kind: 'tool' }>;
      const next: MessagePart = {
        ...tool,
        partialInputJson: (tool.partialInputJson ?? '') + evt.partialJson,
      };
      // Try to upgrade to a parsed `input` once the JSON is well-formed.
      if (!tool.input) {
        try {
          next.input = JSON.parse(next.partialInputJson ?? '');
        } catch {
          /* still streaming — keep partial */
        }
      }
      return {
        ...msg,
        parts: [...msg.parts.slice(0, idx), next, ...msg.parts.slice(idx + 1)],
      };
    }
    case 'tool_result': {
      const idx = msg.parts.findIndex(
        (p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId,
      );
      if (idx < 0) return msg;
      const tool = msg.parts[idx] as Extract<MessagePart, { kind: 'tool' }>;
      const next: MessagePart = {
        ...tool,
        result: { content: evt.content, isError: evt.isError },
        status: evt.isError ? 'error' : 'done',
        subagent: tool.subagent
          ? {
              ...tool.subagent,
              phase: evt.isError ? 'error' : 'done',
              isStreaming: false,
              updatedAt: Date.now(),
            }
          : undefined,
      };
      return {
        ...msg,
        parts: [...msg.parts.slice(0, idx), next, ...msg.parts.slice(idx + 1)],
      };
    }
    case 'tool_progress': {
      if (evt.update.kind !== 'subagent') return msg;
      const idx = msg.parts.findIndex(
        (p) => p.kind === 'tool' && p.toolUseId === evt.toolUseId,
      );
      const tool = idx >= 0
        ? (msg.parts[idx] as Extract<MessagePart, { kind: 'tool' }>)
        : ({
            kind: 'tool',
            toolUseId: evt.toolUseId,
            name: 'Agent',
            status: 'running',
          } as Extract<MessagePart, { kind: 'tool' }>);
      const now = Date.now();
      const existing =
        tool.subagent && tool.subagent.execId === evt.update.execId
          ? tool.subagent
          : {
              execId: evt.update.execId,
              agentSlug: evt.update.agentSlug,
              agentName: evt.update.agentName,
              phase: 'spawning' as const,
              detail: undefined,
              startedAt: now,
              updatedAt: now,
              parts: [] as MessagePart[],
              isStreaming: true,
              stopReason: undefined,
              usage: undefined,
              latestCallUsage: undefined,
              error: undefined,
              errorInfo: undefined,
            };

      let nextSub = {
        ...existing,
        agentSlug: evt.update.agentSlug || existing.agentSlug,
        agentName: evt.update.agentName ?? existing.agentName,
        phase: evt.update.phase ?? existing.phase,
        detail: evt.update.detail ?? existing.detail,
        updatedAt: evt.update.at ?? now,
      };

      if (evt.update.event) {
        const nested = applyNestedEvent(nextSub.parts, evt.update.event);
        nextSub = {
          ...nextSub,
          parts: nested.parts,
          usage: nested.usage ?? nextSub.usage,
          latestCallUsage: nested.latestCallUsage ?? nextSub.latestCallUsage,
          stopReason: nested.stopReason ?? nextSub.stopReason,
          error: nested.error ?? nextSub.error,
          errorInfo: nested.errorInfo ?? nextSub.errorInfo,
          isStreaming: nested.isStreaming ?? nextSub.isStreaming,
        };
      }

      if (evt.update.phase === 'done' || evt.update.phase === 'error') {
        nextSub.isStreaming = false;
      }

      const next: MessagePart = {
        ...tool,
        subagent: nextSub,
      };

      const parts =
        idx >= 0
          ? [...msg.parts.slice(0, idx), next, ...msg.parts.slice(idx + 1)]
          : [...msg.parts, next];
      return {
        ...msg,
        parts,
      };
    }
    case 'turn_done': {
      return {
        ...msg,
        isStreaming: false,
        // Defensive fallback: pi-server's agent_end historically emitted turn_done
        // without a stopReason field. Guard here so a missing stopReason never
        // leaves the message in a zombie state that the interrupt detector fires on.
        stopReason: evt.stopReason ?? 'stop',
        usage: evt.usage,
        durationMs: msg.createdAt != null ? Date.now() - msg.createdAt : undefined,
      };
    }
    case 'assistant_usage': {
      // Per-call usage from the latest API round in this turn — used by
      // the context badge to report real prompt size (vs the aggregate
      // sum on `turn_done` which can exceed the context window for
      // tool-heavy turns).
      return { ...msg, latestCallUsage: evt.usage };
    }
    case 'error': {
      return {
        ...msg,
        isStreaming: false,
        errorInfo: evt.error,
        // Keep `error` populated for legacy renderers / external readers.
        error: evt.error.message,
        durationMs: msg.createdAt != null ? Date.now() - msg.createdAt : undefined,
      };
    }
    default:
      return msg;
  }
}

/**
 * Chat state for a specific session id. Pass `null` for an unsaved fresh
 * conversation — the session is created on first send.
 */
export interface CompactionNotice {
  at: number;
  trigger: 'manual' | 'auto';
  preTokens: number;
  postTokens?: number;
}

export function useChat(
  sessionId: string | null,
  defaultProjectIdForNewSession?: string | null,
) {
  const defaultProjectIdRef = useRef<string | null | undefined>(
    defaultProjectIdForNewSession,
  );
  defaultProjectIdRef.current = defaultProjectIdForNewSession;
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isStreaming, setIsStreaming] = useState(false);
  /** turnId of the in-flight send for the *visible* session. */
  const [streamingTurnId, setStreamingTurnId] = useState<string | null>(null);
  const [lastCompaction, setLastCompaction] = useState<CompactionNotice | null>(null);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(sessionId);
  /** Track compaction markers we've already created to prevent duplicates. */
  const seenCompactionEvents = useRef<Set<string>>(new Set());
  /**
   * State-backed mirror of `streamingBySession`'s key set. Lets consumers
   * (e.g. SessionsPanel) render a "running" indicator on every session that
   * has an active turn, regardless of which one the user is viewing.
   */
  const [streamingSessionIds, setStreamingSessionIds] = useState<
    ReadonlySet<string>
  >(() => new Set());

  // Planning workflow state (session-scoped source of truth in refs below)
  const [activePlan, setActivePlan] = useState<Plan | null>(null);
  const [showPhaseApproval, setShowPhaseApproval] = useState(false);
  const [phaseAwaitingApproval, setPhaseAwaitingApproval] = useState<Phase | null>(null);
  const [showPlanRevision, setShowPlanRevision] = useState(false);
  const [latestRevision, setLatestRevision] = useState<PlanRevision | null>(null);
  const [planError, setPlanError] = useState<{ message: string; phaseId?: string; recoverable: boolean; suggestedAction?: string } | null>(null);

  /**
   * All chat state is keyed by app session id. Streaming events from main
   * route into the right bucket via {@link turnIdToSession}, so a session
   * can keep streaming in the background while the user views another.
   */
  const messagesBySession = useRef<Map<string, ChatMessage[]>>(new Map());
  const streamingBySession = useRef<Map<string, { turnId: string }>>(new Map());
  const turnIdToSession = useRef<Map<string, string>>(new Map());
  const sdkSessionIdBySession = useRef<Map<string, string>>(new Map());
  const titleBySession = useRef<Map<string, string | undefined>>(new Map());
  const activePlanBySession = useRef<Map<string, Plan>>(new Map());
  const planAnchorTurnBySession = useRef<Map<string, string>>(new Map());
  const lastSendBySession = useRef<
    Map<string, { args: SendArgs; assistantId: string }>
  >(new Map());
  /** Sessions for which we've already kicked title generation. */
  const titledRef = useRef<Set<string>>(new Set());

  /**
   * Closure-stable mirror for the chat-event listener. The listener
   * subscribes once at mount and routes events into the right bucket
   * regardless of which session is currently visible.
   */
  const activeSessionIdRef = useRef<string | null>(sessionId);
  activeSessionIdRef.current = activeSessionId;

  const findLastAssistantTurnId = useCallback((sid: string): string | null => {
    const bucket = messagesBySession.current.get(sid) ?? [];
    for (let i = bucket.length - 1; i >= 0; i--) {
      const msg = bucket[i];
      if (msg.role === 'assistant' && msg.markerKind !== 'compaction') {
        return msg.id;
      }
    }
    return null;
  }, []);

  const getOrResolvePlanAnchorTurnId = useCallback((sid: string): string | null => {
    const existing = planAnchorTurnBySession.current.get(sid);
    if (existing) return existing;
    const fromStream = streamingBySession.current.get(sid)?.turnId;
    if (fromStream) return fromStream;
    return findLastAssistantTurnId(sid);
  }, [findLastAssistantTurnId]);

  const setSessionPlan = useCallback((sid: string, plan: Plan | null, options?: { resetAnchor?: boolean }) => {
    if (!plan) {
      activePlanBySession.current.delete(sid);
      planAnchorTurnBySession.current.delete(sid);
      if (sid === activeSessionIdRef.current) {
        setActivePlan(null);
      }
      return;
    }

    activePlanBySession.current.set(sid, plan);

    const shouldResetAnchor = !!options?.resetAnchor;
    if (shouldResetAnchor) {
      planAnchorTurnBySession.current.delete(sid);
    }
    const anchor = getOrResolvePlanAnchorTurnId(sid);
    if (anchor) {
      planAnchorTurnBySession.current.set(sid, anchor);
    }

    if (sid === activeSessionIdRef.current) {
      setActivePlan(plan);
    }
  }, [getOrResolvePlanAnchorTurnId]);

  const getPlanForMessage = useCallback((sid: string | null | undefined, messageId: string): Plan | null => {
    if (!sid) return null;
    const plan = activePlanBySession.current.get(sid);
    if (!plan) return null;
    const anchor = planAnchorTurnBySession.current.get(sid);
    if (!anchor || anchor !== messageId) return null;
    return plan;
  }, []);

  /** Force a re-render so retry-state pills can refresh on demand. */
  const [, bump] = useState(0);
  const forceRerender = useCallback(() => bump((n) => n + 1), []);

  /**
   * Snapshot the current keys of `streamingBySession` into a fresh Set so
   * the React-tracked `streamingSessionIds` state notifies subscribers.
   * Call this at every mutation site of `streamingBySession.current`.
   */
  const syncStreamingIds = useCallback(() => {
    setStreamingSessionIds(new Set(streamingBySession.current.keys()));
  }, []);

  /**
   * Debounced checkpoint persistence. During a stream, every event mutates
   * the in-memory bucket but only `turn_done` would otherwise hit disk.
   * If the app is killed mid-turn the placeholder stays empty forever.
   *
   * The checkpoint flushes the trailing assistant message every ~1 s via
   * `replaceLastMessage` so a kill-mid-turn loses at most that window.
   * Cancelled when the turn completes (final state is written immediately).
   */
  const checkpointTimers = useRef<Map<string, ReturnType<typeof setTimeout>>>(
    new Map(),
  );
  const CHECKPOINT_DEBOUNCE_MS = 1000;

  const flushCheckpoint = useCallback(async (sid: string): Promise<void> => {
    const timer = checkpointTimers.current.get(sid);
    if (timer) {
      clearTimeout(timer);
      checkpointTimers.current.delete(sid);
    }
    const turnId = streamingBySession.current.get(sid)?.turnId;
    if (!turnId) return;
    const bucket = messagesBySession.current.get(sid);
    const msg = bucket?.find((m) => m.id === turnId);
    if (!msg) return;
    const stored: StoredMessage = chatToStored(msg);
    if (!stored.content) stored.content = partsToContent(msg.parts);
    try {
      await replaceLastMessage(sid, stored);
    } catch {
      /* transient — next checkpoint will catch up */
    }
  }, []);

  const scheduleCheckpoint = useCallback(
    (sid: string) => {
      if (checkpointTimers.current.has(sid)) return; // already pending
      const t = setTimeout(() => {
        void flushCheckpoint(sid);
      }, CHECKPOINT_DEBOUNCE_MS);
      checkpointTimers.current.set(sid, t);
    },
    [flushCheckpoint],
  );

  const flushAllCheckpoints = useCallback(async (): Promise<void> => {
    const ids = Array.from(checkpointTimers.current.keys());
    await Promise.all(ids.map((id) => flushCheckpoint(id)));
  }, [flushCheckpoint]);

  // Expose a global so the main process can drive a synchronous-ish flush
  // through `webContents.executeJavaScript` from its `before-quit` handler.
  // Returns a Promise that executeJavaScript will await before resolving.
  useEffect(() => {
    (window as unknown as { __flushPendingChat?: () => Promise<void> })
      .__flushPendingChat = flushAllCheckpoints;
    return () => {
      delete (window as unknown as { __flushPendingChat?: () => Promise<void> })
        .__flushPendingChat;
    };
  }, [flushAllCheckpoints]);

  const maybeAutoGenerateTitle = useCallback(async (sid: string) => {
    if (titledRef.current.has(sid)) return;

    const last = lastSendBySession.current.get(sid);
    const slug = last?.args.connection.slug;
    if (!slug) return;

    const allMessages = messagesBySession.current.get(sid) ?? [];
    const completedAssistantTurns = allMessages.filter(
      (m) => m.role === 'assistant' && !m.errorInfo && !m.isStreaming,
    ).length;
    if (completedAssistantTurns !== 1) return; // only on the very first turn

    const firstUser = allMessages.find((m) => m.role === 'user');
    if (!firstUser) return;
    const firstUserText = partsToContent(firstUser.parts);

    const data = await loadFullSession(sid);
    if (!data) return;
    if (!isAutoGeneratedTitle(data.meta.title, firstUserText)) return;

    titledRef.current.add(sid);
    try {
      const title = await window.api.chat.generateTitle({
        connectionSlug: slug,
        messages: buildTitleSample(allMessages),
        sessionId: sid,
        cwd: data.meta.workingDirectory,
      });
      if (title) {
        await updateSessionMeta(sid, { title });
        titleBySession.current.set(sid, title);
      }
    } catch {
      titledRef.current.delete(sid); // allow retry next turn on transient failures
    }
  }, []);

  // Session-switch: render the bucket if cached, else load from disk.
  useEffect(() => {
    setActiveSessionId(sessionId);
    if (!sessionId) {
      setMessages([]);
      setIsStreaming(false);
      setStreamingTurnId(null);
      setActivePlan(null);
      return;
    }

    // Fresh `send()` may have just primed this bucket — never clobber it
    // with a disk read (the assistant message is mid-stream and won't be
    // persisted until `turn_done`).
    const cached = messagesBySession.current.get(sessionId);
    if (cached) {
      setMessages(cached);
      const stream = streamingBySession.current.get(sessionId);
      setIsStreaming(!!stream);
      setStreamingTurnId(stream?.turnId ?? null);
      setActivePlan(activePlanBySession.current.get(sessionId) ?? null);
      if (
        activePlanBySession.current.has(sessionId) &&
        !planAnchorTurnBySession.current.has(sessionId)
      ) {
        const anchor = findLastAssistantTurnId(sessionId);
        if (anchor) {
          planAnchorTurnBySession.current.set(sessionId, anchor);
        }
      }
      return;
    }

    let cancelled = false;
    loadFullSession(sessionId).then((data) => {
      if (cancelled) return;
      if (!data) {
        messagesBySession.current.set(sessionId, []);
        setMessages([]);
        setIsStreaming(false);
        setStreamingTurnId(null);
        setSessionPlan(sessionId, null);
        return;
      }
      let msgs = data.messages.map(chatFromStored);
      
      // Populate deduplication set from loaded compaction markers to prevent
      // creating duplicates if the same turn triggers compaction again.
      for (const msg of msgs) {
        if (msg.markerKind === 'compaction' && msg.compactionMeta) {
          // Find the assistant message this marker is associated with.
          // It should be right before the marker in the list.
          const idx = msgs.indexOf(msg);
          const prevMsg = idx > 0 ? msgs[idx - 1] : null;
          if (prevMsg && prevMsg.role === 'assistant') {
            const key = `${sessionId}:${prevMsg.id}:${msg.compactionMeta.preTokens}`;
            seenCompactionEvents.current.add(key);
          }
        }
      }
      
      // Recovery: if the trailing assistant message is a "zombie" (no
      // stop reason, no error info — the turn never reached `turn_done`),
      // mark it interrupted so the user sees a Retry button. This catches
      // app-killed-mid-turn cases that the debounced checkpoint missed.
      const last = msgs[msgs.length - 1];
      if (
        last &&
        last.role === 'assistant' &&
        !last.stopReason &&
        !last.errorInfo &&
        !last.error &&
        !streamingBySession.current.has(sessionId)
      ) {
        const errInfo: AgentError = {
          code: 'unknown_error',
          title: 'Turn was interrupted',
          message:
            'The previous turn did not finish — the app was closed or the connection dropped before completion. Click Retry to run it again.',
          canRetry: true,
        };
        const fixed: ChatMessage = {
          ...last,
          isStreaming: false,
          stopReason: 'aborted',
          errorInfo: errInfo,
          error: errInfo.message,
        };
        msgs = [...msgs.slice(0, -1), fixed];
        // Persist the recovery so the disk reflects the same state on next
        // load and downstream readers (e.g. title gen) see a closed turn.
        const stored = chatToStored(fixed);
        // Preserve the original createdAt so replaceLastMessage does not bump
        // meta.lastMessageAt to Date.now(), which would re-sort the session list
        // and cause the session to jump position after every app restart.
        // Fall back to chatToStored's Date.now() only for very old messages
        // that predate the createdAt-in-ChatMessage field.
        if (last.createdAt != null) stored.createdAt = last.createdAt;
        if (!stored.content) stored.content = partsToContent(fixed.parts);
        void replaceLastMessage(sessionId, stored);
      }
      messagesBySession.current.set(sessionId, msgs);
      if (data.meta.sdkSessionId) {
        sdkSessionIdBySession.current.set(sessionId, data.meta.sdkSessionId);
      }
      titleBySession.current.set(sessionId, data.meta.title);
      setMessages(msgs);
      const stream = streamingBySession.current.get(sessionId);
      setIsStreaming(!!stream);
      setStreamingTurnId(stream?.turnId ?? null);

      if (
        activePlanBySession.current.has(sessionId) &&
        !planAnchorTurnBySession.current.has(sessionId)
      ) {
        const anchor = findLastAssistantTurnId(sessionId);
        if (anchor) {
          planAnchorTurnBySession.current.set(sessionId, anchor);
        }
      }
      setActivePlan(activePlanBySession.current.get(sessionId) ?? null);
    });
    return () => {
      cancelled = true;
    };
  }, [sessionId, findLastAssistantTurnId, setSessionPlan]);

  // Subscribe once to chat events; route to the right session by turnId.
  useEffect(() => {
    if (!window.api?.chat) return;

    return window.api.chat.onEvent((evt: ChatStreamEvent) => {
      // Compaction is between-turn metadata, not part of any message.
      if (evt.type === 'compaction') {
        setLastCompaction({
          at: Date.now(),
          trigger: evt.trigger,
          preTokens: evt.preTokens,
          postTokens: evt.postTokens,
        });
        
        const sid = turnIdToSession.current.get(evt.id);
        if (!sid) return;

        // Deduplicate: Pi SDK can emit multiple compaction_end events for
        // the same turn (on retries, errors, etc.). Create a unique key
        // from session + turn + preTokens to detect duplicates.
        const eventKey = `${sid}:${evt.id}:${evt.preTokens}`;
        if (seenCompactionEvents.current.has(eventKey)) {
          // Already created a marker for this compaction event.
          console.debug('[useChat] Duplicate compaction event ignored:', eventKey);
          return;
        }
        seenCompactionEvents.current.add(eventKey);

        const marker: ChatMessage = {
          id: newId(),
          role: 'assistant',
          parts: [],
          markerKind: 'compaction',
          compactionMeta: {
            trigger: evt.trigger,
            preTokens: evt.preTokens,
            postTokens: evt.postTokens,
            durationMs: evt.durationMs,
          },
        };

        const prevMsgs = messagesBySession.current.get(sid) ?? [];
        
        // Mid-turn insertion: find the assistant message with this turn ID
        // and insert the marker right after it. If not found (compaction
        // between turns), append at the end.
        const turnMsgIndex = prevMsgs.findIndex((m) => m.id === evt.id);
        const insertionMode = turnMsgIndex >= 0 ? 'after-turn' : 'append';
        const next =
          turnMsgIndex >= 0
            ? [
                ...prevMsgs.slice(0, turnMsgIndex + 1),
                marker,
                ...prevMsgs.slice(turnMsgIndex + 1),
              ]
            : [...prevMsgs, marker];

        console.debug(
          '[useChat] Compaction marker created:',
          {
            eventKey,
            trigger: evt.trigger,
            preTokens: evt.preTokens,
            postTokens: evt.postTokens,
            turnId: evt.id,
            insertionMode,
            turnMsgIndex,
          },
        );

        messagesBySession.current.set(sid, next);
        if (sid === activeSessionIdRef.current) setMessages(next);
        
        // Persist the entire message array to maintain correct order on disk.
        // Using appendMessage() would write the marker to the end, losing the
        // mid-turn position on reload.
        void rewriteMessages(sid, next.map(chatToStored));
        return;
      }

      const sid = turnIdToSession.current.get(evt.id);
      if (!sid) {
        // Event for a turn we no longer track (post-reload, post-abort).
        return;
      }

      const prev = messagesBySession.current.get(sid);
      if (!prev) return;
      const next = prev.map((m) => (m.id === evt.id ? applyEvent(m, evt) : m));
      messagesBySession.current.set(sid, next);

      if (sid === activeSessionIdRef.current) {
        setMessages(next);
      }

      // Mid-stream checkpoint so a kill / window-close mid-turn doesn't
      // lose the partial reply. Coalesces; turn_done cancels the timer.
      if (evt.type !== 'turn_done' && evt.type !== 'error') {
        scheduleCheckpoint(sid);
      }

      if (evt.type === 'turn_done' || evt.type === 'error') {
        // Defer to next tick so the bucket reflects the just-applied event.
        queueMicrotask(() => {
          // Cancel any pending mid-stream checkpoint — the final write below
          // is authoritative.
          const pending = checkpointTimers.current.get(sid);
          if (pending) {
            clearTimeout(pending);
            checkpointTimers.current.delete(sid);
          }
          const bucket = messagesBySession.current.get(sid);
          const final = bucket?.find((m) => m.id === evt.id);
          if (final) {
            const stored: StoredMessage = chatToStored(final);
            if (!stored.content) stored.content = partsToContent(final.parts);
            void replaceLastMessage(sid, stored);
            if (evt.sessionId) {
              sdkSessionIdBySession.current.set(sid, evt.sessionId);
              void updateSessionMeta(sid, { sdkSessionId: evt.sessionId });
            }
            if (evt.type === 'turn_done' && !final.errorInfo) {
              void maybeAutoGenerateTitle(sid);
            }
          }
          // Stream lifecycle ends regardless of whether the bubble matched.
          streamingBySession.current.delete(sid);
          turnIdToSession.current.delete(evt.id);
          syncStreamingIds();
          if (sid === activeSessionIdRef.current) {
            setIsStreaming(false);
            setStreamingTurnId(null);
          }
          // Keep-awake gate is global; only release when nothing is streaming.
          if (streamingBySession.current.size === 0) {
            void window.api.app.setAgentActive(false);
          }
          // Notification only for the session that just finished.
          if (
            getAppSettings().notificationsEnabled &&
            !document.hasFocus()
          ) {
            const isError = evt.type === 'error';
            const title = isError ? 'Agent turn failed' : 'Agent turn complete';
            const sessionName = titleBySession.current.get(sid)?.trim();
            const body = isError
              ? evt.error.title || evt.error.message
              : sessionName || 'Your assistant has finished responding.';
            void window.api.app.notify(title, body);
          }
        });
      }
    });
  }, [maybeAutoGenerateTitle]);

  // Listen for planning workflow events
  useEffect(() => {
    if (!window.api?.planning) return;

    const unsubCreated = window.api.planning.onPlanCreated((sid: string, plan: Plan) => {
      setSessionPlan(sid, plan, { resetAnchor: true });
    });

    const unsubUpdated = window.api.planning.onPlanUpdated((sid: string, plan: Plan) => {
      setSessionPlan(sid, plan);
    });

    const unsubPhaseUpdated = window.api.planning.onPhaseUpdated((sid: string, planId: string, phase: Phase) => {
      const current = activePlanBySession.current.get(sid);
      if (!current || current.id !== planId) return;
      const updated = { ...current, phases: [...current.phases] };
      const index = updated.phases.findIndex((p) => p.id === phase.id);
      if (index < 0) return;
      updated.phases[index] = phase;
      setSessionPlan(sid, updated);
    });

    const unsubRevised = window.api.planning.onPlanRevised((sid: string, plan: Plan, revision: PlanRevision) => {
      setSessionPlan(sid, plan);
      if (sid === activeSessionIdRef.current) {
        setLatestRevision(revision);
        setShowPlanRevision(true);
        // Auto-hide revision notification after 10 seconds
        setTimeout(() => setShowPlanRevision(false), 10000);
      }
    });

    const unsubCompleted = window.api.planning.onPlanCompleted((sid: string, planId: string) => {
      const current = activePlanBySession.current.get(sid);
      if (!current || current.id !== planId) return;
      setSessionPlan(sid, { ...current, status: 'completed' });
    });

    const unsubCancelled = window.api.planning.onPlanCancelled((sid: string, planId: string) => {
      const current = activePlanBySession.current.get(sid);
      if (current && current.id !== planId) return;
      setSessionPlan(sid, null);
      if (sid === activeSessionIdRef.current) {
        setShowPhaseApproval(false);
        setPhaseAwaitingApproval(null);
      }
    });

    const unsubError = window.api.planning.onPlanError((sid: string, planId: string, error: string, phaseId?: string) => {
      const current = activePlanBySession.current.get(sid);
      if (!current || current.id !== planId) return;
      setSessionPlan(sid, { ...current, status: 'error' });
      if (sid === activeSessionIdRef.current) {
        setPlanError({
          message: error,
          phaseId,
          recoverable: true,
          suggestedAction: 'Review the error and choose a recovery action.',
        });
      }
    });

    return () => {
      unsubCreated();
      unsubUpdated();
      unsubPhaseUpdated();
      unsubRevised();
      unsubCompleted();
      unsubCancelled();
      unsubError();
    };
  }, [setSessionPlan]);

  // Load active plan on session change
  useEffect(() => {
    if (!activeSessionId || !window.api?.planning) return;

    window.api.planning.getActivePlan(activeSessionId)
      .then((plan: Plan | null) => setSessionPlan(activeSessionId, plan))
      .catch((err) => console.error('Failed to load active plan:', err));
  }, [activeSessionId, setSessionPlan]);

  const send = useCallback(
    async ({
      text,
      connection,
      model,
      cwd,
      maxTurns,
      permissionMode,
      attachments: drafts,
      agentText,
      intentTag,
    }: SendArgs) => {
      const trimmed = text.trim();
      const draftsList = drafts ?? [];
      if (!trimmed && draftsList.length === 0) return;
      const promptForAgent = (agentText ?? trimmed).trim();

      let sid = activeSessionIdRef.current;
      const isFreshSession = !sid;
      if (!sid) {
        // If the user is filtering to a specific project, the new session
        // belongs there explicitly — overrides cwd-based auto-assignment.
        const explicitProjectId = defaultProjectIdRef.current;
        const created = await createSession({
          workingDirectory: cwd,
          ...(explicitProjectId ? { projectId: explicitProjectId } : {}),
        });
        sid = created.id;
        // Seed the bucket BEFORE flipping activeSessionId so the
        // session-switch effect (and any prop-driven re-run from App)
        // sees a populated bucket and skips the disk reload.
        messagesBySession.current.set(sid, []);
        activeSessionIdRef.current = sid;
        setActiveSessionId(sid);
      }
      await updateSessionMeta(sid, {
        permissionMode,
        connectionSlug: connection.slug,
        model,
        ...(cwd ? { workingDirectory: cwd } : {}),
      });

      // Attachments — failures abort the send with an inline error bubble.
      const stored: StoredAttachment[] = [];
      for (const d of draftsList) {
        try {
          stored.push(await storeAttachment(sid, d));
        } catch (e) {
          const errMsg = e instanceof Error ? e.message : String(e);
          const errInfo: AgentError = {
            code: 'unknown_error',
            title: 'Failed to attach file',
            message: errMsg,
            canRetry: true,
          };
          const errBubble: ChatMessage = {
            id: newId(),
            role: 'assistant',
            parts: [],
            isStreaming: false,
            errorInfo: errInfo,
            error: errMsg,
          };
          const prev = messagesBySession.current.get(sid) ?? [];
          const next = [...prev, errBubble];
          messagesBySession.current.set(sid, next);
          if (sid === activeSessionIdRef.current) setMessages(next);
          return;
        }
      }

      const userMsg: ChatMessage = {
        id: newId(),
        role: 'user',
        parts: trimmed ? [{ kind: 'text', text: trimmed }] : [],
        attachments: stored.length > 0 ? stored : undefined,
        intentTag,
      };
      const assistantId = newId();
      const assistantMsg: ChatMessage = {
        id: assistantId,
        role: 'assistant',
        parts: [],
        isStreaming: true,
        model,
        createdAt: Date.now(),
      };

      const prev = messagesBySession.current.get(sid) ?? [];
      const next = [...prev, userMsg, assistantMsg];
      messagesBySession.current.set(sid, next);
      streamingBySession.current.set(sid, { turnId: assistantId });
      turnIdToSession.current.set(assistantId, sid);
      syncStreamingIds();
      lastSendBySession.current.set(sid, {
        args: {
          text: trimmed,
          connection,
          model,
          cwd,
          maxTurns,
          permissionMode,
          attachments: drafts,
        },
        assistantId,
      });

      if (sid === activeSessionIdRef.current) {
        setMessages(next);
        setIsStreaming(true);
        setStreamingTurnId(assistantId);
      }
      forceRerender(); // refresh canRetry across sessions
      void window.api.app.setAgentActive(true);

      await appendMessage(sid, chatToStored(userMsg));
      await appendMessage(sid, chatToStored(assistantMsg));

      // Refresh cached title for fresh sessions (main rewrites
      // `meta.title` from the first user message inside `appendMessage`).
      if (isFreshSession || !titleBySession.current.get(sid)) {
        void loadFullSession(sid).then((d) => {
          if (d) titleBySession.current.set(sid, d.meta.title);
        });
      }

      try {
        await window.api.chat.send({
          id: assistantId,
          connectionSlug: connection.slug,
          model,
          prompt: promptForAgent,
          cwd,
          resumeSessionId: sdkSessionIdBySession.current.get(sid),
          maxTurns,
          permissionMode,
          sessionId: sid,
          attachments: stored.length > 0 ? stored : undefined,
        });
      } catch (e) {
        const errMsg = e instanceof Error ? e.message : String(e);
        // The IPC bridge itself failed (rare — e.g. main-process crash).
        const errInfo: AgentError = {
          code: 'unknown_error',
          title: 'Could not start the turn',
          message:
            'The request failed before the agent could begin streaming. Try again.',
          canRetry: true,
          originalError: errMsg,
        };
        const cur = messagesBySession.current.get(sid) ?? [];
        const updated = cur.map((m) =>
          m.id === assistantId
            ? { ...m, isStreaming: false, errorInfo: errInfo, error: errMsg }
            : m,
        );
        messagesBySession.current.set(sid, updated);
        void replaceLastMessage(sid, {
          id: assistantId,
          role: 'assistant',
          content: '',
          error: errMsg,
          errorInfo: errInfo,
          createdAt: Date.now(),
        });
        streamingBySession.current.delete(sid);
        turnIdToSession.current.delete(assistantId);
        syncStreamingIds();
        if (sid === activeSessionIdRef.current) {
          setMessages(updated);
          setIsStreaming(false);
          setStreamingTurnId(null);
        }
        if (streamingBySession.current.size === 0) {
          void window.api.app.setAgentActive(false);
        }
      }
    },
    [forceRerender],
  );

  /**
   * Inject a user message into the running turn (mid-turn steer). The
   * message is delivered via the SDK's streaming-input mechanism — the
   * model picks it up on its next iteration. We render an inline ghost
   * user bubble so the user has a visible record that it landed; the
   * SDK doesn't acknowledge consumption explicitly so this is the best
   * feedback signal available.
   *
   * In-memory only — steer messages aren't persisted as separate turns
   * (the agent's subsequent response already reflects them).
   */
  const steer = useCallback(
    async (
      text: string,
      attachmentDrafts: DraftAttachment[] = [],
    ): Promise<{ ok: boolean; reason?: string }> => {
      const sid = activeSessionIdRef.current;
      if (!sid) return { ok: false, reason: 'no active session' };
      const stream = streamingBySession.current.get(sid);
      if (!stream) return { ok: false, reason: 'no running turn' };
      const trimmed = text.trim();
      if (!trimmed && attachmentDrafts.length === 0)
        return { ok: false, reason: 'empty message' };

      // Store draft attachments before sending (same path as normal send).
      const stored: StoredAttachment[] = [];
      for (const d of attachmentDrafts) {
        try {
          stored.push(await storeAttachment(sid, d));
        } catch {
          // skip unreadable drafts rather than blocking the steer
        }
      }

      const result = await window.api.chat.steer(
        stream.turnId,
        trimmed,
        stored.length > 0 ? stored : undefined,
      );
      if (!result.ok) return result;

      // Insert a ghost user bubble right BEFORE the running assistant so
      // the visual order reads "you said X then the assistant kept going".
      const current = messagesBySession.current.get(sid) ?? [];
      const idx = current.findIndex((m) => m.id === stream.turnId);
      const steerMsg: ChatMessage = {
        id: newId(),
        role: 'user',
        parts: trimmed ? [{ kind: 'text', text: trimmed }] : [],
        attachments: stored.length > 0 ? stored : undefined,
        intentTag: 'steer',
      };
      const next =
        idx >= 0
          ? [...current.slice(0, idx), steerMsg, ...current.slice(idx)]
          : [...current, steerMsg];
      messagesBySession.current.set(sid, next);
      if (sid === activeSessionIdRef.current) setMessages(next);
      
      // Persist steer message at the correct position in the message list.
      // The assistant's response will follow after the steer, so we need to
      // maintain this order on disk for correct replay.
      void rewriteMessages(sid, next.map(chatToStored));
      
      return result;
    },
    [],
  );

  const abort = useCallback(async () => {
    const sid = activeSessionIdRef.current;
    if (!sid) return;
    const stream = streamingBySession.current.get(sid);
    if (!stream) return;
    await window.api?.chat.abort(stream.turnId);
    streamingBySession.current.delete(sid);
    turnIdToSession.current.delete(stream.turnId);
    syncStreamingIds();

    // Finalise the assistant bubble in memory: clear the spinner and stamp
    // a stop reason so the UI shows the aborted state rather than a ghost
    // message with no content.
    const current = messagesBySession.current.get(sid) ?? [];
    const updated = current.map((m) =>
      m.id === stream.turnId
        ? { ...m, isStreaming: false, stopReason: 'aborted', durationMs: m.createdAt != null ? Date.now() - m.createdAt : undefined }
        : m,
    );
    messagesBySession.current.set(sid, updated);

    // Persist the finalised state so the bubble survives a reload.
    const final = updated.find((m) => m.id === stream.turnId);
    if (final) {
      const stored = chatToStored(final);
      if (!stored.content) stored.content = partsToContent(final.parts);
      void replaceLastMessage(sid, stored);
    }

    if (sid === activeSessionIdRef.current) {
      setMessages(updated);
      setIsStreaming(false);
      setStreamingTurnId(null);
    }
    if (streamingBySession.current.size === 0) {
      void window.api?.app.setAgentActive(false);
    }
  }, []);

  /**
   * Re-run the *current session's* last failed turn with the same
   * connection / model / cwd. Drops the trailing failed user+assistant
   * pair from memory and disk so the new turn slots in cleanly.
   */
  const retry = useCallback(
    async (fallback?: {
      connection: ConnectionMeta;
      model: string;
      cwd?: string;
      maxTurns?: number;
      permissionMode: PermissionMode;
    }) => {
      const sid = activeSessionIdRef.current;
      if (!sid) return;
      if (streamingBySession.current.has(sid)) return;

      const last = lastSendBySession.current.get(sid);
      if (last) {
        // Hot path: retry within the same app run — replay the captured
        // SendArgs verbatim. Drops the failed pair so the new turn slots
        // cleanly into the conversation.
        const failedAssistantId = last.assistantId;
        const current = messagesBySession.current.get(sid) ?? [];
        const idx = current.findIndex((m) => m.id === failedAssistantId);
        const userBeforeId =
          idx > 0 && current[idx - 1].role === 'user'
            ? current[idx - 1].id
            : null;

        const cutFrom =
          idx > 0 && current[idx - 1].role === 'user' ? idx - 1 : idx;
        const trimmed = idx < 0 ? current : current.slice(0, cutFrom);
        messagesBySession.current.set(sid, trimmed);
        if (sid === activeSessionIdRef.current) setMessages(trimmed);

        const dropFromId = userBeforeId ?? failedAssistantId;
        await truncateSessionMessages(sid, dropFromId);

        await send(last.args);
        return;
      }

      // Cold path: app was relaunched after an interrupted turn. The
      // recovery code in the session-load effect rewrote the trailing
      // assistant as `errorInfo.canRetry: true`, but `lastSendBySession`
      // is empty. Reconstruct the SendArgs from the bucket's last user
      // message + caller-supplied connection/model.
      if (!fallback) return;
      const current = messagesBySession.current.get(sid) ?? [];
      // Find the trailing assistant and the user message before it.
      let assistantIdx = -1;
      for (let i = current.length - 1; i >= 0; i--) {
        if (current[i].role === 'assistant') {
          assistantIdx = i;
          break;
        }
      }
      const userIdx = assistantIdx > 0 ? assistantIdx - 1 : -1;
      if (userIdx < 0 || current[userIdx].role !== 'user') return;
      const userMsg = current[userIdx];
      const userText = partsToContent(userMsg.parts).trim();
      if (!userText) return;

      // Drop both messages from memory + disk before re-sending so the
      // SDK's resume-by-sessionId picks up at the prior user message.
      const trimmed = current.slice(0, userIdx);
      messagesBySession.current.set(sid, trimmed);
      if (sid === activeSessionIdRef.current) setMessages(trimmed);
      await truncateSessionMessages(sid, userMsg.id);

      await send({
        text: userText,
        connection: fallback.connection,
        model: fallback.model,
        cwd: fallback.cwd,
        maxTurns: fallback.maxTurns,
        permissionMode: fallback.permissionMode,
      });
    },
    [send],
  );

  // Hot-path retry — true when the visible session has captured SendArgs
  // from a prior `send()` in this app run. The cold path (post-reload
  // interrupted turn) requires caller-supplied fallback args and is
  // surfaced via `errorInfo.canRetry` on the message itself, not this flag.
  const canRetry =
    !!activeSessionId &&
    lastSendBySession.current.has(activeSessionId) &&
    !streamingBySession.current.has(activeSessionId);

  return {
    messages,
    isStreaming,
    /** turnId of the in-flight send for the visible session — null when idle. */
    streamingTurnId,
    /** Every session id with an in-flight turn, including non-visible ones. */
    streamingSessionIds,
    activeSessionId,
    send,
    abort,
    retry,
    /** Mid-turn steer; appends a visible "Injected" user bubble on success. */
    steer,
    /** True iff the visible session has a failed turn we can replay. */
    canRetry,
    /** Most recent compaction event (or null) — UI auto-fades it. */
    lastCompaction,
    // Planning workflow state
    activePlan,
    getPlanForMessage,
    showPhaseApproval,
    phaseAwaitingApproval,
    showPlanRevision,
    latestRevision,
    planError,
    setShowPhaseApproval,
    setPhaseAwaitingApproval,
    setShowPlanRevision,
    setPlanError,
  };
}
