// Renderer-side title helpers. Keeps a tiny mirror of the main-process
// `makeTitle` truncation so we can detect "is the current title still the
// default auto-title" without an IPC round-trip.

import { partsToContent } from './chat';
import type { ChatMessage } from './chat';

/** Mirror of `makeTitle` in src/main/storage/sessions.ts. */
export function firstLineTruncateTitle(text: string): string {
  const firstLine = text.trim().split('\n')[0]?.trim() ?? '';
  return firstLine.length > 60
    ? firstLine.slice(0, 57) + '…'
    : firstLine || 'New session';
}

/** True if the title is the placeholder or matches the first-message truncate. */
export function isAutoGeneratedTitle(title: string, firstUserText: string): boolean {
  if (title === 'New session' || !title.trim()) return true;
  return title === firstLineTruncateTitle(firstUserText);
}

/** Sample we send to the title-generation LLM (oldest first, capped). */
export function buildTitleSample(
  messages: ChatMessage[],
): Array<{ role: 'user' | 'assistant'; content: string }> {
  const out: Array<{ role: 'user' | 'assistant'; content: string }> = [];
  for (const m of messages) {
    if (m.errorInfo) continue;
    const text = partsToContent(m.parts).trim();
    if (!text) continue;
    out.push({ role: m.role, content: text });
    if (out.length >= 4) break;
  }
  return out;
}
